from datetime import datetime, timedelta

from freezegun import freeze_time

from crudclient.auth import CustomAuth
from crudclient.testing.auth.oauth_mock import OAuthMock

# --- Test Initialization ---


def test_oauth_mock_init_defaults() -> None:
    """Test default initialization."""
    mock = OAuthMock()
    assert mock.client_id == "client_id"
    assert mock.client_secret == "client_secret"
    assert mock.token_url == "https://example.com/oauth/token"
    assert mock.authorize_url == "https://example.com/oauth/authorize"
    assert mock.redirect_uri == "https://app.example.com/callback"
    assert mock.scope == "read write"

    # Check token manager state (indirectly)
    assert mock.token_manager.current_access_token is not None
    initial_token = mock.token_manager.current_access_token
    assert mock.token_manager.validate_token(initial_token) is True

    # Check auth strategy
    assert isinstance(mock.auth_strategy, CustomAuth)
    headers = mock.auth_strategy.prepare_request_headers()
    assert headers == {"Authorization": f"Bearer {initial_token}"}


# --- Test Configuration Methods ---


def test_with_client_credentials() -> None:
    mock = OAuthMock().with_client_credentials("new_id", "new_secret")
    assert mock.client_id == "new_id"
    assert mock.client_secret == "new_secret"


def test_with_token_url() -> None:
    mock = OAuthMock().with_token_url("https://new.token.url/token")
    assert mock.token_url == "https://new.token.url/token"


def test_with_authorize_url() -> None:
    mock = OAuthMock().with_authorize_url("https://new.auth.url/auth")
    assert mock.authorize_url == "https://new.auth.url/auth"


def test_with_redirect_uri() -> None:
    mock = OAuthMock().with_redirect_uri("https://new.app/callback")
    assert mock.redirect_uri == "https://new.app/callback"


def test_with_scope() -> None:
    mock = OAuthMock().with_scope("profile email")
    assert mock.scope == "profile email"
    # Note: This also updates the scope of the *next* token generated by default,
    # but doesn't change the scope of the *currently* held default token.
    # Re-initializing or explicitly setting token metadata would be needed
    # for the current token's scope to change based on this alone.


def test_with_grant_type() -> None:
    mock = OAuthMock().with_grant_type("client_credentials")
    assert mock.grant_handler.grant_type == "client_credentials"


def test_with_access_token() -> None:
    """Test setting a specific access token."""
    mock = OAuthMock()
    initial_token = mock.token_manager.current_access_token
    mock.with_access_token("new_token_123")

    assert mock.token_manager.current_access_token == "new_token_123"
    assert mock.token_manager.validate_token("new_token_123") is True
    # Check if old token might still be valid if not explicitly revoked/expired
    assert mock.token_manager.validate_token(initial_token) is True

    # Check auth strategy update
    headers = mock.auth_strategy.prepare_request_headers()
    assert headers == {"Authorization": "Bearer new_token_123"}


def test_with_refresh_token() -> None:
    """Test associating a refresh token."""
    mock = OAuthMock().with_access_token("acc_token")
    mock.with_refresh_token("ref_token_abc")
    assert mock.token_manager.current_refresh_token == "ref_token_abc"
    assert mock.token_manager.refresh_tokens["ref_token_abc"] == "acc_token"


def test_with_token_expiration() -> None:
    """Test setting token expiration."""
    with freeze_time("2023-01-01 12:00:00") as frozen_time:
        mock = OAuthMock().with_access_token("exp_token")
        mock.with_token_expiration(expires_in_seconds=60)

        token_data = mock.token_manager.access_tokens["exp_token"]
        assert token_data["expires_at"] == datetime(2023, 1, 1, 12, 1, 0)

        assert mock.token_manager.validate_token("exp_token") is True
        frozen_time.tick(delta=timedelta(seconds=61))
        assert mock.token_manager.validate_token("exp_token") is False


@freeze_time("2023-01-01 12:00:00")
def test_with_expired_token() -> None:
    """Test setting token as already expired."""
    mock = OAuthMock().with_access_token("already_expired")
    mock.with_expired_token()

    token_data = mock.token_manager.access_tokens["already_expired"]
    assert token_data["expires_at"] < datetime(2023, 1, 1, 12, 0, 0)
    assert mock.token_manager.validate_token("already_expired") is False


def test_with_required_scopes() -> None:
    """Test setting required scopes for validation."""
    mock = OAuthMock()
    mock.with_required_scopes(["admin"])
    assert mock.scope_validator.required_scopes == {"admin"}
    # Note: Actual validation happens within token_manager or grant_handler


def test_with_available_scopes() -> None:
    """Test setting available scopes."""
    mock = OAuthMock()
    mock.with_available_scopes(["profile", "email", "admin"])
    assert mock.scope_validator.available_scopes == {"profile", "email", "admin"}


# --- Test Verification Methods ---


@freeze_time("2023-01-01 12:00:00")
def test_verify_auth_header_valid() -> None:
    mock = OAuthMock().with_access_token("valid_bearer_token")
    assert mock.verify_auth_header("Bearer valid_bearer_token") is True


def test_verify_auth_header_invalid_prefix() -> None:
    mock = OAuthMock().with_access_token("valid_bearer_token")
    assert mock.verify_auth_header("Basic valid_bearer_token") is False


def test_verify_auth_header_invalid_token() -> None:
    mock = OAuthMock().with_access_token("valid_bearer_token")
    assert mock.verify_auth_header("Bearer invalid_token") is False


@freeze_time("2023-01-01 12:00:00")
def test_verify_auth_header_expired_token() -> None:
    mock = OAuthMock().with_access_token("expired_bearer")
    mock.with_expired_token()
    assert mock.verify_auth_header("Bearer expired_bearer") is False


def test_verify_token_usage() -> None:
    """Test verify_token_usage delegates to token_manager."""
    mock = OAuthMock().with_access_token("usage_token")
    assert mock.verify_token_usage("usage_token") is True
    assert mock.verify_token_usage("invalid_usage_token") is False


# --- Test Base Class Method Implementations ---


def test_get_auth_headers() -> None:
    """Test get_auth_headers returns current bearer token."""
    mock = OAuthMock().with_access_token("current_token")
    assert mock.get_auth_headers() == ("Authorization", "Bearer current_token")


def test_get_auth_headers_no_token() -> None:
    """Test get_auth_headers returns None if no token (edge case)."""
    mock = OAuthMock()
    mock.token_manager.current_access_token = ""  # Force no token (empty string)
    assert mock.get_auth_headers() is None


@freeze_time("2023-01-01 12:00:00")
def test_handle_auth_error_expired_refreshable_base() -> None:
    """Test handle_auth_error uses base refresh simulation."""
    mock = OAuthMock().with_access_token("expired_token")
    mock.with_expired_token()  # Expire the OAuth token
    # Enable base class refresh simulation
    mock.with_refresh_token("base_refresh_key")

    assert mock.is_token_expired() is True  # Checks base class expired flag
    assert mock.can_refresh_token() is True  # Checks base class refresh possibility

    handled = mock.handle_auth_error(None)  # type: ignore
    assert handled is True  # Base refresh simulation succeeded
    assert mock.refresh_attempts == 1


@freeze_time("2023-01-01 12:00:00")
def test_handle_auth_error_expired_not_refreshable_base() -> None:
    """Test handle_auth_error when base refresh not possible."""
    mock = OAuthMock().with_access_token("expired_token")
    mock.with_expired_token()  # Expire the OAuth token
    # DO NOT enable base class refresh simulation

    assert mock.is_token_expired() is True
    assert mock.can_refresh_token() is False  # Base refresh not possible

    handled = mock.handle_auth_error(None)  # type: ignore
    assert handled is False


@freeze_time("2023-01-01 12:00:00")
def test_handle_auth_error_not_expired_base() -> None:
    """Test handle_auth_error when token not expired (base check)."""
    mock = OAuthMock().with_access_token("valid_token")
    mock.with_token_expiration(3600)  # Not expired
    mock.with_refresh_token("base_refresh_key")  # Enable base refresh

    assert mock.is_token_expired() is False  # Base check

    handled = mock.handle_auth_error(None)  # type: ignore
    assert handled is False


def test_get_auth_strategy() -> None:
    """Test getting the underlying auth strategy."""
    mock = OAuthMock()
    strategy = mock.get_auth_strategy()
    assert isinstance(strategy, CustomAuth)
    # Check if the callback produces the correct header
    headers = strategy.prepare_request_headers()
    assert "Authorization" in headers
    assert headers["Authorization"].startswith("Bearer ")
