# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: check-docstrings
        name: Check docstrings are only in .pyi files
        stages: [pre-commit]
        language: system
        entry: python hooks/check_docstrings.py
        types: [python]
        files: ^crudclient/.*\.py$

      - id: check-stub-files
        name: Check .py files have matching .pyi files
        stages: [pre-commit]
        language: system
        entry: python hooks/check_stub_files.py
        types: [python]
        files: ^crudclient/.*\.py$

#      - id: check-file-length
#        name: Check .py files are ≤ 300 lines
#        stages: [pre-commit]
#        language: system
#        entry: python hooks/check_file_length.py
#        types: [python]
#
      - id: autoflake
        name: autoflake
        stages: [pre-commit]
        language: system
        entry: poetry run autoflake --remove-all-unused-imports --in-place --recursive
        types: [python]

      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: poetry run isort --profile black
        types: [python]

      - id: black
        name: black
        stages: [pre-commit]
        language: system
        entry: poetry run black
        types: [python, pyi]

      - id: flake8
        name: flake8
        stages: [pre-commit]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: poetry run mypy
        types: [python, pyi]
        require_serial: true

      - id: pytest
        name: pytest (changed files)
        stages: [pre-commit]
        language: system
        entry: python -c "import sys; from subprocess import run; files = ' '.join(sys.argv[1:]); run(f'poetry run pytest {files} -v --no-header --durations=3', shell=True)" --
        types: [python]
        files: ^(crudclient/|tests/unit/).*\.py$
        pass_filenames: true
        verbose: true

      - id: pytest-cov
        name: pytest with coverage
        stages: [pre-push]
        language: system
        entry: poetry run pytest tests/unit/ --cov --cov-report=term-missing --cov-fail-under=85 --cov-branch --no-header --durations=5
        types: [python]
        pass_filenames: false
        verbose: true
