[mypy]
files = crudclient, tests
ignore_missing_imports = true

# Example of per-module override:
# [mypy-tests.integration.oneflow_resources.setup]
# ignore_errors = true
# disable_error_code = assignment, override, return-value, call-overload, index