[pytest]
testpaths =
    crudclient/*/tests
    tests/


# Set verbosity level (optional)
addopts = -ra -q -n auto

# Specify patterns for test file discovery (optional)
python_files = test_*.py

markers =
    no_parallel: mark test to run sequentially, not in parallel with others (used by custom xdist scheduler)
