name: Test DevContainer Build

on:
  push:
    branches:
      - '**'
    paths:
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build DevContainer
        run: |
          docker build .devcontainer/ -f .devcontainer/Dockerfile --platform linux/amd64 --tag devcontainer-test:${{ matrix.os }}

      - name: Run DevContainer
        run: |
          docker run --rm devcontainer-test:${{ matrix.os }} sleep 5
