name: Test DevContainer Build

on:
  push:
    branches:
      - '**'
    paths:
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Devcontainer CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Build and Test DevContainer
        run: |
          devcontainer up --workspace-folder . --skip-post-create

      - name: Validate DevContainer
        run: |
          devcontainer exec --workspace-folder . /usr/local/py-utils/bin/poetry --version
