name: Test DevContainer Build

on:
  push:
    branches:
      - '**'
    paths:
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          open --background -a Docker
          while ! docker system info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 10
          done


      - name: Set up Devcontainer CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Build and Test DevContainer
        run: |
          devcontainer up --workspace-folder . --skip-post-create

      - name: Validate DevContainer
        run: |
          devcontainer exec --workspace-folder . /usr/local/py-utils/bin/poetry --version
